import { CampaignProposalPositionConditionCreateModel } from './campaign_proposal_position_conditions.create.model';

export class CampaignProposalPositionConditionUpdateModel extends CampaignProposalPositionConditionCreateModel {}