export const ACTIVITY = Object.freeze({
  UPDATE_INFO: 'UPDATE_INFO',

  ASSIGN_OWNER_ORGANIZATION: 'ACCEPT_OWNER_ORGANIZATION',

  CREATE_CHAPTER: 'CREATE_CHAPTER',
  UPDATE_CHAPTER: 'UPDATE_CHAPTER',
  DELETE_CHAPTER: 'DELETE_CHAPTER',
  INVITE_USER_CHAPTER: 'INVITE_USER_CHAPTER',
  REMOVE_USER_CHAPTER: 'REMOVE_USER_CHAPTER',
  INVITE_ORGANIZATION_CHAPTER: 'INVITE_ORGANIZATION_CHAPTER',
  REMOVE_ORGANIZATION_CHAPTER: 'REMOVE_ORGANIZATION_CHAPTER',

  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  VERIFY_ORGANIZATION: 'VERIFY_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  INVITE_USER_ORGANIZATION: 'INVITE_USER_ORGANIZATION',
  ACCEPT_ORGANIZATION_USER: 'ACCEPT_ORGANIZATION_USER',
  REMOVE_USER_ORGANIZATION: 'REMOVE_USER_ORGANIZATION',
});
