import { Module } from '@nestjs/common';

import { TypeOrmModule } from '@nestjs/typeorm';
import { AppController } from './app.controller';
import { AppService } from './app.service';

import { CacheModule } from '@nestjs/cache-manager';
import { ThrottlerModule } from '@nestjs/throttler';
import { redisStore } from 'cache-manager-redis-store';
import { CommonModule } from './app/common/common.module';
import { MediaModule } from './app/media/media.module';
import { RecruitingModule } from './app/recruiting/recruiting.module';
import { IdentityModule } from './app/identity/identity.module';
import { CampaignCandidateEntity, UserEntity } from './app/recruiting/entities';
import { IdeUserEntity, OrganizationEntity, WorkspaceEntity } from './app/identity/entities';
import { CommonUserEntity, CustomFieldEntity, CustomFieldTypeEntity, CustomFieldValueEntity, ResourceCustomFieldEntity, ResourceCustomFieldValueEntity } from './app/common/entities';
import { MediaUserEntity } from './app/media/entities';

@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'mysql',
      host: '127.0.0.1',
      port: 3306,
      username: 'root',
      password: 'root',
      database: 'gce_dev',
      entities: [
        CommonUserEntity,
        MediaUserEntity,
        IdeUserEntity,
        OrganizationEntity,
        UserEntity,
        // AwardEntity,
        // AlbumEntity,
        // ChapterEntity,
        // CommentEntity,
        // CommunityEntity,
        // InvitationUserEntity,
        // EventEntity,
        // MessageEntity,
        // NewsEntity,
        // NewsSummaryEntity,
        // OpportunityEntity,
        // UserNotificationEntity,
        // ProjectNotificationEntity,
        // NotificationEntity,
        // TagEntity,
        // HiddenSourceEntity,
        // FollowEntity,
        // MessageGroupEntity,
        // IndustryEntity,
        // ServiceEntity,
        // ShortcutEntity,
        // FriendRequestEntity,
        // FriendEntity,
        // CityEntity,
        // CountryEntity,
        // UserHistoryEntity,
        // UserChapterEntity,
        // UserOtpHistoryEntity,
        // MemberVerifyHistoryEntity,
        // ReactionEntity,
        // ReportEntity,
        // ReportResourceEntity,
        // OrganizationChapterEntity,
        // OrganizationUserEntity,
        WorkspaceEntity,
        // PositionEntity,
        // IAMGroupEntity,
        // IAMGroupUserEntity,
        // IAMRoleEntity,
        // IAMPermissionEntity,
        // ImageEntity,
        // BidEntity,
        // ParticipateEntity,
        // SearchHistoryEntity,
        // NewsTagEntity,
        // KeepEntity,
        // MentionEntity,
        // // // PMP
        // CategoryEntity,
        // IssueCommentEntity,
        // IssueEntity,
        // MilestoneEntity,
        // PriorityEntity,
        // ProjectEntity,
        // StatusEntity,
        // VersionEntity,
        // WikiEntity,
        // ChecklistEntity,
        //Product
        // ProductCategoryEntity,
        // UserAddressEntity,
        // UserFavoriteProductCategoryEntity,
        // ProductEntity,
        // DailyEntity,
        // ProductSummaryEntity,
        //CommonModule
        CustomFieldEntity,
        CustomFieldTypeEntity,
        CustomFieldValueEntity,
        ResourceCustomFieldEntity,
        ResourceCustomFieldValueEntity,
        // ActivityEntity,
        // RatingEntity,
        // UserSummaryEntity,
        // OrganizationSummaryEntity,
        // ClickEntity,
        // ViewEntity,
        // InterestedEntity,
        // ProductSummaryEntity,
        // //message
        // HiddenMessageGroupEntity,
        // BlockEntity,
        // MessageGroupUsersEntity,
        // MessageGroupEntity,
        // MessageImageEntity,
        // MessagePinEntity,
        // MessageReactionEntity,
        // MessageReportEntity,
        // MessageResourceReportEntity,
        // MessageSummaryEntity,
        // MessageUserReadEntity,
        // MessageEntity,
        // UserNicknameEntity,
        // UserStatusEntity,
        // ProductEntity,
        // BrandEntity,
        // ProductTypeEntity,
        // CategoryEntity,
        // OptionEntity,
        // OptionValueEntity,
        // ProductVariantEntity,
        // CustomerEntity,
        // CartEntity,
        // CartItemEntity,
        // OrderEntity,
        // OrderItemEntity,
        // OrganizationConnectEntity,
        // ComboEntity,
        // UserEntity,
        // CommentEntity,
        // InventoryEntity,
        // PackageEntity,
        // PackageItemEntity,
        // DeliveryEntity,
        // DeliveryItemEntity,
        // ReturnEntity,
        // ReturnItemEntity,
        // ShortReviewEntity,
        // HagTagEntity,
        // LikeEntity,
        // BannerEntity,
        // NotificationEntity,
        // QuoteEntity,
        // QuoteItemEntity,
        // RequestQuoteEntity,
        // RequestQuoteItemEntity,
        // WishlistEntity,
        // OrderStatusEntity,
        // OrderStatusHistoryEntity,
        // ActivityEntity,
        // FirebaseTokenEntity,
        // ChapterJoinRequestEntity,
        //ATS
        // VacancyEntity,
        // CandidateEntity,
        //Candidate
        // CandidateLoginEntity,

        CampaignCandidateEntity,
      ],
      synchronize: true,
      logging: false,
    }),

    CacheModule.register({
      useFactory: async () =>
        await redisStore({
          ttl: +process.env.REDIS_TTL || 300,
          socket: {
            host: process.env.REDIS_HOST || '14.225.206.155',
            port: +process.env.REDIS_PORT || 6379,
          },
        }),
    }),
    IdentityModule,
    RecruitingModule,
    MediaModule,
    CommonModule,
    ThrottlerModule.forRoot([
      {
        name: 'short',
        ttl: 1000,
        limit: 3,
      },
      {
        name: 'medium',
        ttl: 10000,
        limit: 20,
      },
      {
        name: 'long',
        ttl: 60000,
        limit: 100,
      },
    ]),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
